class RequestKeys {
  static String Cpassword = 'confirm_password';
  static String Otp = 'otp';
  static String userId = 'user_id';
  static String Id = 'id';
  static String password = 'password';
  static String deviceid = 'device_id';
  static String ipaddress = 'ip_addres';
  static String email = 'email';
  static String mobile = 'mobile';

  static String newPassword = 'new';
  static String lname = 'lastname';
  static String fname = 'firstname';
  // static String userid = 'user_id';
  static String firstname = 'first_name';
  static String lastname = 'last_name';
  static String city = 'city';
  static String photographertype = 'photographer_type';
  static String companyname = 'compny_name';
  static String companyphone = 'company_phone';
  static String companyaddress = 'company_address';
  static String companyEmail = 'company_email_id';
  static String facebookLink = 'facebook_page';
  static String instagramLink = 'instagram_page';
  static String youtubeLink = 'youtube_link';
  static String tncLink = 'term_condition';
  static String country = 'country';
  static String perdaycharge = 'per_day_charges';
  static String type = 'type';
  static String companyImage = 'company_image';
  static String profileImage = 'profile_pic';
  static String clientName = 'client_name';
  static String outPut = 'output';
  static String amount = 'amount';
  static String typePhotographer = 'event[]';
  static String date  = 'date[]';
  static String event  = 'event';
}